/*
 * mls.c -- main program of Modern Little Smalltalk
 */


#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <signal.h>

#include "common.h"
#include "machine.h"
#include "memory.h"
#include "filein.h"
#include "compiler.h"
#include "ui.h"


/**************************************************************/


void sigintHandler(int sig) {
  signal(SIGINT, sigintHandler);
  debugMachine = true;
}


void installSigintHandler(void) {
  signal(SIGINT, sigintHandler);
}


/**************************************************************/


static void version(char *myself) {
  printf("%s version %d.%d (compiled %s)\n",
         myself, MAJOR_VNUM, MINOR_VNUM, __DATE__);
}


static void help(char *myself) {
  printf("Usage: %s [options]\n", myself);
  printf("Options:\n");
  printf("  --image <image file>    set image file name\n");
  printf("  --debug                 start virtual machine in debug mode\n");
  printf("  --memory                show memory statistics\n");
  printf("  --filein                show file-in details\n");
  printf("  --source                show source given to compiler\n");
  printf("  --tokens                show token stream within compiler\n");
  printf("  --tree                  show syntax tree within compiler\n");
  printf("  --vars                  show variable info within compiler\n");
  printf("  --code                  show code generated by compiler\n");
  printf("  --version               show version and terminate\n");
  printf("  --help                  show this help and terminate\n");
}


int main(int argc, char *argv[]) {
  int i;
  char *imageFileName;

  printf("Modern Little Smalltalk %d.%d\n",
         MAJOR_VNUM, MINOR_VNUM);
  imageFileName = DFLT_IMG_NAME;
  for (i = 1; i < argc; i++) {
    if (*argv[i] == '-') {
      /* option */
      if (strcmp(argv[i], "--image") == 0) {
        if (i == argc - 1) {
          sysError("no image file name specified");
        }
        imageFileName = argv[++i];
      } else
      if (strcmp(argv[i], "--debug") == 0) {
        debugMachine = true;
      } else
      if (strcmp(argv[i], "--memory") == 0) {
        debugMemory = true;
      } else
      if (strcmp(argv[i], "--filein") == 0) {
        debugFileIn = true;
      } else
      if (strcmp(argv[i], "--source") == 0) {
        debugSource = true;
      } else
      if (strcmp(argv[i], "--tokens") == 0) {
        debugTokens = true;
      } else
      if (strcmp(argv[i], "--tree") == 0) {
        debugTree = true;
      } else
      if (strcmp(argv[i], "--vars") == 0) {
        debugVars = true;
      } else
      if (strcmp(argv[i], "--code") == 0) {
        debugCode = true;
      } else
      if (strcmp(argv[i], "--version") == 0) {
        version(argv[0]);
        exit(0);
      } else
      if (strcmp(argv[i], "--help") == 0) {
        help(argv[0]);
        exit(0);
      } else {
        sysError("unknown option '%s', try '%s --help'",
                 argv[i], argv[0]);
      }
    } else {
      /* file */
      sysError("illegal file argument '%s', try '%s --help'",
               argv[i], argv[0]);
    }
  }
  installSigintHandler();
  enableGC = true;
  initMemory(imageFileName);
  run();
  exitMemory(imageFileName);
  printf("Bye...\n");
  return 0;
}
